builds:
  - binary: bullet
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  files:
    - LICENSE.md

release:
  github:
    owner: FurqanSoftware
    name: bullet
